import type { Metadata } from "next";
import "../app/styles/globals.css";
import {Lexend_Deca} from "next/font/google";

const lexendDeca = Lexend_Deca({
    variable: '--font-lexend-deca-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${lexendDeca.variable}`} >
        {children}
        </body>
        </html>
    );
}
