import type {Metadata} from "next";
import "./styles/globals.css";
import {Lexend_Deca, Nunito} from "next/font/google";
import {Providers} from "./providers";
import {Toaster, ErrorBoundary} from "@/shared/ui";

const lexendDeca = Lexend_Deca({
    variable: '--font-lexend-deca-sans',
    subsets: ['latin'],
})

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Task Sync",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${lexendDeca.variable} ${nunito.variable}`}>
            <ErrorBoundary>
                <Providers>
                    <div className="px-6 relative">
                        <div className="absolute inset-0 -z-10 pointer-events-none">
                            <div className="absolute top-0 right-0 w-36 h-36 bg-yellow-100 rounded-full blur-3xl"/>
                            <div className="absolute top-[6rem] left-0 w-36 h-36 bg-green-100 rounded-full blur-3xl"/>
                            <div className="absolute top-[15rem] right-0 w-36 h-36 bg-blue-500 rounded-full opacity-25 blur-3xl"/>
                            <div className="absolute top-[30rem] left-1/3 transform -translate-x-1/2 -translate-y-1/2 w-36 h-36
                             bg-blue-500 opacity-25 rounded-full blur-3xl"/>
                        </div>
                        {children}
                        <Toaster/>
                    </div>
                </Providers>
            </ErrorBoundary>
        </body>
        </html>
    );
}
